name: provider_setup
description: Flutter Skeleton using Provider State Management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  go_router: ^13.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^8.0.2
  http: ^1.2.1
  firebase_messaging: ^14.8.0
  firebase_core: ^2.28.0
  firebase_analytics: ^10.10.0
  firebase_crashlytics: ^3.5.0
  camera_platform_interface: ^2.7.4
  cached_network_image: ^3.3.1
  future_progress_dialog: ^0.2.1
  flutter_native_splash: ^2.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  leak_tracker_flutter_testing: 3.0.3
  leak_tracker_testing: 3.0.1



  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/


flutter_native_splash:
  color: "#ffffff"
  color_dark: "#042a49"
  image: assets/images/AbeBooks.png
  android_gravity: center
  ios_content_mode: center
  # dart pub run flutter_native_splash:create

  android_12:
   image: assets/images/AbeBooks.png
  android: true
  ios: true
  web: true
  fullscreen: true

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
